'use client'

import { useParams, useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import { Download, CheckCircle, AlertTriangle, ArrowLeft, Trophy, Shield } from 'lucide-react'
import Navigation from '@/components/Navigation'
import ScoreRing from '@/components/ScoreRing'
import ScoreBar from '@/components/ScoreBar'
import clsx from 'clsx'
import { useState } from 'react'

// Mock data — replace with real API call
const MOCK_DATA = {
  rfp_id: '',
  requirement: 'We need 500 brake sensors by 2026-09-30. Specs: ABS wheel speed sensor, IP67, CAN bus output.',
  category: 'Sensors',
  quantity: 500,
  deadline: '2026-09-30',
  approval_required: false,
  top2: [
    {
      rank: 1,
      supplier_id: 'SUP005',
      supplier_name: 'AutoSensor Global',
      total_score: 67.4,
      flags: [],
      scores: { price: 72.1, quality: 68.4, delivery: 81.2, compliance: 90.0 },
    },
    {
      rank: 2,
      supplier_id: 'SUP003',
      supplier_name: 'Continental Tech',
      total_score: 65.3,
      flags: ['High Price'],
      scores: { price: 58.2, quality: 72.0, delivery: 74.5, compliance: 90.0 },
    },
  ],
}

const SCORE_BARS = (scores: Record<string, number>) => [
  { label: 'Price', weight: '30%', value: scores.price, delay: 0 },
  { label: 'Quality', weight: '30%', value: scores.quality, delay: 0.1 },
  { label: 'Delivery', weight: '20%', value: scores.delivery, delay: 0.2 },
  { label: 'Compliance', weight: '20%', value: scores.compliance, delay: 0.3 },
]

export default function RecommendationPage() {
  const params = useParams()
  const router = useRouter()
  const rfpId = params.id as string
  const data = { ...MOCK_DATA, rfp_id: rfpId }

  const [approved, setApproved] = useState<null | boolean>(null)

  const handleApprove = () => setApproved(true)
  const handleReject = () => setApproved(false)

  return (
    <div className="min-h-screen bg-[#EDE8DC]">
      <Navigation />

      <main className="max-w-6xl mx-auto px-6 py-10">
        {/* Breadcrumb */}
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.35 }}
          className="flex items-center gap-2 text-xs text-[#7A7265] mb-6"
        >
          <button onClick={() => router.push('/')} className="hover:text-[#2C2C2C] transition-colors flex items-center gap-1">
            <ArrowLeft className="w-3 h-3" />
            Dashboard
          </button>
          <span>/</span>
          <button onClick={() => router.push(`/rfp/${rfpId}/progress`)} className="hover:text-[#2C2C2C] transition-colors">
            {rfpId}
          </button>
          <span>/</span>
          <span className="text-[#2C2C2C]">Recommendation</span>
        </motion.div>

        {/* Page title */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, delay: 0.05 }}
          className="mb-8"
        >
          <h1 className="text-2xl font-light text-[#2C2C2C]">Supplier Recommendation</h1>
          <p className="text-sm text-[#7A7265] mt-1">
            Generated by AI · {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })} · {data.top2.length + 4} suppliers evaluated
          </p>
        </motion.div>

        <div className="grid grid-cols-5 gap-6">
          {/* LEFT: Summary + Approval + Downloads */}
          <div className="col-span-2 flex flex-col gap-4">
            {/* RFP Summary */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.1 }}
              className="bg-[#F5F1E8] border border-[#D4CBB8]/50 rounded-xl p-4 shadow-warm-sm"
            >
              <p className="text-xs tracking-[0.15em] uppercase text-[#7A7265] font-medium mb-3">RFP Summary</p>
              <div className="space-y-2">
                <div>
                  <span className="text-xs text-[#7A7265]">RFP ID</span>
                  <p className="text-sm font-mono text-[#2C2C2C]">{rfpId}</p>
                </div>
                <div>
                  <span className="text-xs text-[#7A7265]">Requirement</span>
                  <p className="text-sm text-[#2C2C2C] leading-relaxed">{data.requirement}</p>
                </div>
                <div className="grid grid-cols-2 gap-2 pt-1">
                  <div>
                    <span className="text-xs text-[#7A7265]">Quantity</span>
                    <p className="text-sm text-[#2C2C2C]">{data.quantity} units</p>
                  </div>
                  <div>
                    <span className="text-xs text-[#7A7265]">Deadline</span>
                    <p className="text-sm text-[#2C2C2C]">{data.deadline}</p>
                  </div>
                </div>
              </div>
            </motion.div>

            {/* Approval card */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.2 }}
              className={clsx(
                'rounded-xl p-4 shadow-warm-sm border-l-4',
                approved === true
                  ? 'bg-[#F0F7EE] border-[#5C8A4A] border border-[#5C8A4A]/20'
                  : approved === false
                  ? 'bg-[#FDF2F0] border-[#A63D2F] border border-[#A63D2F]/20'
                  : data.approval_required
                  ? 'bg-[#FDF8EE] border-[#E8A020] border border-[#E8A020]/20'
                  : 'bg-[#F0F7EE] border-[#5C8A4A] border border-[#5C8A4A]/20'
              )}
            >
              {approved === true ? (
                <>
                  <div className="flex items-center gap-2 mb-1">
                    <CheckCircle className="w-4 h-4 text-[#5C8A4A]" />
                    <span className="text-sm font-medium text-[#5C8A4A]">Contract Approved</span>
                  </div>
                  <p className="text-xs text-[#7A7265]">Contract awarded to {data.top2[0].supplier_id}</p>
                </>
              ) : approved === false ? (
                <>
                  <div className="flex items-center gap-2 mb-1">
                    <AlertTriangle className="w-4 h-4 text-[#A63D2F]" />
                    <span className="text-sm font-medium text-[#A63D2F]">RFP Rejected</span>
                  </div>
                  <p className="text-xs text-[#7A7265]">This RFP has been rejected. No contract awarded.</p>
                </>
              ) : data.approval_required ? (
                <>
                  <div className="flex items-center gap-2 mb-1">
                    <AlertTriangle className="w-4 h-4 text-[#E8A020]" />
                    <span className="text-sm font-medium text-[#2C2C2C]">Human Review Required</span>
                  </div>
                  <p className="text-xs text-[#7A7265] mb-3">Risk flags detected. Please review before awarding.</p>
                  <div className="flex flex-col gap-2">
                    <button
                      onClick={handleApprove}
                      className="w-full h-9 rounded-lg bg-[#E8A020] text-white text-sm font-medium hover:bg-[#C97B1A] transition-colors"
                    >
                      ✓ Approve & Award
                    </button>
                    <button
                      onClick={handleReject}
                      className="w-full h-9 rounded-lg border border-[#D4CBB8] text-[#7A7265] text-sm hover:bg-[#EDE8DC] transition-colors"
                    >
                      ✗ Reject
                    </button>
                  </div>
                </>
              ) : (
                <>
                  <div className="flex items-center gap-2 mb-1">
                    <CheckCircle className="w-4 h-4 text-[#5C8A4A]" />
                    <span className="text-sm font-medium text-[#5C8A4A]">Auto-Approved</span>
                  </div>
                  <p className="text-xs text-[#7A7265]">No risk flags detected. Contract auto-awarded to {data.top2[0].supplier_id}.</p>
                </>
              )}
            </motion.div>

            {/* Downloads */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: 0.3 }}
              className="bg-[#F5F1E8] border border-[#D4CBB8]/50 rounded-xl p-4 shadow-warm-sm"
            >
              <p className="text-xs tracking-[0.15em] uppercase text-[#7A7265] font-medium mb-3">Documents</p>
              <div className="flex flex-col gap-2">
                <button className="flex items-center justify-between w-full px-3 py-2.5 rounded-lg border border-[#D4CBB8] hover:border-[#E8A020]/40 hover:bg-[#EDE8DC] transition-all group">
                  <span className="text-sm text-[#2C2C2C]">RFP Document</span>
                  <div className="flex items-center gap-1.5 text-[#E8A020] text-xs">
                    <Download className="w-3.5 h-3.5" />
                    <span>.docx</span>
                  </div>
                </button>
                <button className="flex items-center justify-between w-full px-3 py-2.5 rounded-lg border border-[#D4CBB8] hover:border-[#E8A020]/40 hover:bg-[#EDE8DC] transition-all group">
                  <span className="text-sm text-[#2C2C2C]">Recommendation Report</span>
                  <div className="flex items-center gap-1.5 text-[#E8A020] text-xs">
                    <Download className="w-3.5 h-3.5" />
                    <span>.docx</span>
                  </div>
                </button>
              </div>
            </motion.div>
          </div>

          {/* RIGHT: Supplier cards */}
          <div className="col-span-3 flex flex-col gap-4">
            <p className="text-xs tracking-[0.15em] uppercase text-[#7A7265] font-medium">
              Top Recommendations
            </p>

            {data.top2.map((supplier, i) => (
              <motion.div
                key={supplier.supplier_id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.15 + i * 0.12 }}
                className={clsx(
                  'bg-[#F5F1E8] border rounded-xl p-5 shadow-warm-sm',
                  i === 0
                    ? 'border-[#E8A020]/30 shadow-warm'
                    : 'border-[#D4CBB8]/50'
                )}
              >
                {/* Badge + supplier */}
                <div className="flex items-start justify-between mb-4">
                  <div className="flex items-center gap-2">
                    {i === 0 ? (
                      <Trophy className="w-4 h-4 text-[#E8A020]" />
                    ) : (
                      <Shield className="w-4 h-4 text-[#7A7265]" />
                    )}
                    <span className={clsx(
                      'text-xs font-medium tracking-wide',
                      i === 0 ? 'text-[#E8A020]' : 'text-[#7A7265]'
                    )}>
                      {i === 0 ? 'RANK 1 — RECOMMENDED CHOICE' : 'RANK 2 — BACKUP OPTION'}
                    </span>
                  </div>
                  {supplier.flags.length > 0 && (
                    <span className="flex items-center gap-1 px-2 py-0.5 bg-[#FDF8EE] border border-[#E8A020]/30 rounded-full text-xs text-[#C97B1A]">
                      <AlertTriangle className="w-2.5 h-2.5" />
                      {supplier.flags[0]}
                    </span>
                  )}
                  {supplier.flags.length === 0 && (
                    <span className="flex items-center gap-1 px-2 py-0.5 bg-[#F0F7EE] border border-[#5C8A4A]/20 rounded-full text-xs text-[#5C8A4A]">
                      <CheckCircle className="w-2.5 h-2.5" />
                      No Flags
                    </span>
                  )}
                </div>

                <div className="flex gap-5">
                  {/* Score ring */}
                  <div className="shrink-0">
                    <ScoreRing
                      score={supplier.total_score}
                      size={100}
                      strokeWidth={7}
                      color={i === 0 ? '#E8A020' : '#C4B89E'}
                    />
                  </div>

                  {/* Info + bars */}
                  <div className="flex-1 min-w-0">
                    <div className="mb-3">
                      <h3 className="text-base font-medium text-[#2C2C2C]">{supplier.supplier_name}</h3>
                      <span className="text-xs font-mono text-[#7A7265]">{supplier.supplier_id}</span>
                    </div>

                    <div className="flex flex-col gap-2">
                      {SCORE_BARS(supplier.scores).map(bar => (
                        <ScoreBar
                          key={bar.label}
                          label={bar.label}
                          weight={bar.weight}
                          value={bar.value}
                          delay={bar.delay + i * 0.15}
                        />
                      ))}
                    </div>
                  </div>
                </div>

                {/* Action button */}
                {i === 0 && !data.approval_required && approved === null && (
                  <motion.button
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: 0.8 }}
                    onClick={handleApprove}
                    className="mt-4 w-full h-10 rounded-lg bg-[#E8A020] text-white text-sm font-medium hover:bg-[#C97B1A] transition-colors"
                  >
                    Award Contract to {supplier.supplier_id}
                  </motion.button>
                )}
                {i === 1 && (
                  <button className="mt-4 w-full h-10 rounded-lg border border-[#D4CBB8] text-[#7A7265] text-sm hover:bg-[#EDE8DC] transition-colors">
                    Select as Alternative
                  </button>
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </main>
    </div>
  )
}
